BEGIN TRY
DECLARE @N1 INT, @N2 INT, @N3 INT;
DECLARE @MAI_MARE INT;
SET @N1 = 60 / RAND();
SET @N2 = 60 / RAND();
SET @N3 = 60 / RAND();

--To get an error--
--SET @N1 = 60
--SET @N2 = 60

IF @N1 = @N2 RAISERROR('Eroare', 16,1);
ELSE IF @N1 > @N2 AND @N1 > @N3 SET @MAI_MARE = @N1
ELSE IF @N2 > @N1 AND @N2 > @N3 SET @MAI_MARE = @N2
ELSE IF @N3 > @N2 AND @N3 > @N1 SET @MAI_MARE = @N3

END TRY

BEGIN CATCH
PRINT 'ERROR LINE: ' + CAST(ERROR_LINE() AS VARCHAR(20));
PRINT 'ERROR NUMBER: ' + CAST(ERROR_NUMBER() AS VARCHAR(20));
END CATCH;

PRINT @N1;
PRINT @N2;
PRINT @N3;
PRINT 'Mai mare = ' + CAST(@MAI_MARE AS VARCHAR(20));